### ISSUE TITLE
No graph

### ISSUE THREAD

**Issue by ghost** [hairmare/zabbix-icecast#3]
Hello,

We have no graph on Zabbix Server.

The issue : 

GOOD 
> zabbix_get -s xx.xx.xx.xx -k 'icecast.global.client_connections'
45050581 

NOT WORKING
> zabbix_get -s xx.xx.xx.xx -k 'icecast.source.listeners[*]'
ZBX_NOTSUPPORTED

We are using Zabbix 3.2

Any ideas ?

Thanks

**Comment by hairmare** [comment]
You need to replace the `*` in `icecast.source.listeners[*]` with the name of an actual mount point like `/my-stream.mp3` as in the following example.

```
zabbix_get -s xx.xx.xx.xx -k 'icecast.source.listeners[/my-stream.mp3]'
```
